// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           22
// Async Callback (empty):               1
// Total number of exported functions:  25

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    association_manager
    (
        init => init
        upgrade => upgrade
        registerAssociation => register_association
        registerMember => register_member
        removeMember => remove_member
        createVotingSession => create_voting_session
        castVote => cast_vote
        castVoteBySignature => cast_vote_by_signature
        stopSession => stop_session
        finalizeSession => finalize_session
        getAssocCount => get_assoc_count
        getAssocName => get_assoc_name
        getAssocAdmin => get_assoc_admin
        isMember => is_member
        getMembers => get_members
        getSessionCount => get_session_count
        getSessionStatus => get_session_status
        getSessionDeadline => get_session_deadline
        getSessionMaxChoices => get_session_max_choices
        getSessionResult => get_session_result
        getCandidatesWithVotes => get_candidates_with_votes
        getEligibleVoters => get_eligible_voters
        getHasVoted => get_has_voted
        getVoteCount => get_vote_count
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
